export const SET_LOADING = 'SET_LOADING'
export const REMOVE_LOADING = 'REMOVE_LOADING'
export const SET_USER = 'SET_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const SET_STORAGE = 'SET_STORAGE'
export const GET_STORAGE = 'GET_STORAGE'
export const SET_AUTH_ON = 'SET_AUTH_ON'
export const SET_AUTH_OFF = 'SET_AUTH_OFF'